# Host to use for canonical URL generation (without trailing slash)
host: tech-docs-manual.cloudapps.digital

# Header-related options
show_govuk_logo: false
service_name: Tech docs template
service_link: /

max_toc_heading_level: 3

prevent_indexing: false
