# Host to use for canonical URL generation (without trailing slash)
host: alphagov.github.io/tech-docs-manual

# Header-related options
show_govuk_logo: false
service_name: Tech docs template
service_link: /

max_toc_heading_level: 3

prevent_indexing: false

show_contribution_banner: true
github_repo: alphagov/tech-docs-manual
